<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SkillsStagesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $skillsStages = [
            ['skill_id' => 1, 'skill_name' => 'Thruster', 'stage' => 1, 'stage_label' => '23 kg - 5 reps'],
            ['skill_id' => 1, 'skill_name' => 'Thruster', 'stage' => 2, 'stage_label' => '23 kg - 8 reps'],
            ['skill_id' => 1, 'skill_name' => 'Thruster', 'stage' => 3, 'stage_label' => '29 kg - 4 reps'],
            ['skill_id' => 1, 'skill_name' => 'Thruster', 'stage' => 4, 'stage_label' => '32 kg - 3 reps'],
            ['skill_id' => 1, 'skill_name' => 'Thruster', 'stage' => 5, 'stage_label' => '28 kg - 10 reps'],
            ['skill_id' => 1, 'skill_name' => 'Thruster', 'stage' => 6, 'stage_label' => '35 kg - 6 reps'],
            ['skill_id' => 1, 'skill_name' => 'Thruster', 'stage' => 7, 'stage_label' => '40 kg - 3 reps'],
            ['skill_id' => 1, 'skill_name' => 'Thruster', 'stage' => 8, 'stage_label' => '38 kg - 7 reps'],
            ['skill_id' => 1, 'skill_name' => 'Thruster', 'stage' => 9, 'stage_label' => '43 kg - 5 reps'],
            ['skill_id' => 1, 'skill_name' => 'Thruster', 'stage' => 10, 'stage_label' => '40 kg - 9 reps'],
            ['skill_id' => 1, 'skill_name' => 'Thruster', 'stage' => 11, 'stage_label' => '47 kg - 6 reps'],
            ['skill_id' => 1, 'skill_name' => 'Thruster', 'stage' => 12, 'stage_label' => '44 kg - 9 reps'],
            ['skill_id' => 1, 'skill_name' => 'Thruster', 'stage' => 13, 'stage_label' => '53 kg - 5 reps'],
            ['skill_id' => 1, 'skill_name' => 'Thruster', 'stage' => 14, 'stage_label' => '58 kg - 4 reps'],
            ['skill_id' => 1, 'skill_name' => 'Thruster', 'stage' => 15, 'stage_label' => '48 kg - 11 reps'],
            ['skill_id' => 1, 'skill_name' => 'Thruster', 'stage' => 16, 'stage_label' => '57 kg - 7 reps'],
            ['skill_id' => 1, 'skill_name' => 'Thruster', 'stage' => 17, 'stage_label' => '65 kg - 4 reps'],
            ['skill_id' => 1, 'skill_name' => 'Thruster', 'stage' => 18, 'stage_label' => '60 kg - 8 reps'],
            ['skill_id' => 1, 'skill_name' => 'Thruster', 'stage' => 19, 'stage_label' => '66 kg - 6 reps'],
            ['skill_id' => 1, 'skill_name' => 'Thruster', 'stage' => 20, 'stage_label' => '60 kg - 10 reps'],
            ['skill_id' => 2, 'skill_name' => 'Push Press', 'stage' => 1, 'stage_label' => '23 kg - 5 reps'],
            ['skill_id' => 2, 'skill_name' => 'Push Press', 'stage' => 2, 'stage_label' => '24 kg - 8 reps'],
            ['skill_id' => 2, 'skill_name' => 'Push Press', 'stage' => 3, 'stage_label' => '30 kg - 4 reps'],
            ['skill_id' => 2, 'skill_name' => 'Push Press', 'stage' => 4, 'stage_label' => '34 kg - 3 reps'],
            ['skill_id' => 2, 'skill_name' => 'Push Press', 'stage' => 5, 'stage_label' => '30 kg - 10 reps'],
            ['skill_id' => 2, 'skill_name' => 'Push Press', 'stage' => 6, 'stage_label' => '38 kg - 6 reps'],
            ['skill_id' => 2, 'skill_name' => 'Push Press', 'stage' => 7, 'stage_label' => '44 kg - 3 reps'],
            ['skill_id' => 2, 'skill_name' => 'Push Press', 'stage' => 8, 'stage_label' => '42 kg - 7 reps'],
            ['skill_id' => 2, 'skill_name' => 'Push Press', 'stage' => 9, 'stage_label' => '48 kg - 5 reps'],
            ['skill_id' => 2, 'skill_name' => 'Push Press', 'stage' => 10, 'stage_label' => '45 kg - 9 reps'],
            ['skill_id' => 2, 'skill_name' => 'Push Press', 'stage' => 11, 'stage_label' => '53 kg - 6 reps'],
            ['skill_id' => 2, 'skill_name' => 'Push Press', 'stage' => 12, 'stage_label' => '50 kg - 9 reps'],
            ['skill_id' => 2, 'skill_name' => 'Push Press', 'stage' => 13, 'stage_label' => '61 kg - 5 reps'],
            ['skill_id' => 2, 'skill_name' => 'Push Press', 'stage' => 14, 'stage_label' => '66 kg - 4 reps'],
            ['skill_id' => 2, 'skill_name' => 'Push Press', 'stage' => 15, 'stage_label' => '55 kg - 11 reps'],
            ['skill_id' => 2, 'skill_name' => 'Push Press', 'stage' => 16, 'stage_label' => '65 kg - 7 reps'],
            ['skill_id' => 2, 'skill_name' => 'Push Press', 'stage' => 17, 'stage_label' => '76 kg - 4 reps'],
            ['skill_id' => 2, 'skill_name' => 'Push Press', 'stage' => 18, 'stage_label' => '69 kg - 8 reps'],
            ['skill_id' => 2, 'skill_name' => 'Push Press', 'stage' => 19, 'stage_label' => '77 kg - 6 reps'],
            ['skill_id' => 2, 'skill_name' => 'Push Press', 'stage' => 20, 'stage_label' => '70 kg - 10 reps'],
            ['skill_id' => 3, 'skill_name' => 'Snatch', 'stage' => 1, 'stage_label' => '29 kg - 5 reps'],
            ['skill_id' => 3, 'skill_name' => 'Snatch', 'stage' => 2, 'stage_label' => '29 kg - 8 reps'],
            ['skill_id' => 3, 'skill_name' => 'Snatch', 'stage' => 3, 'stage_label' => '36 kg - 4 reps'],
            ['skill_id' => 3, 'skill_name' => 'Snatch', 'stage' => 4, 'stage_label' => '40 kg - 3 reps'],
            ['skill_id' => 3, 'skill_name' => 'Snatch', 'stage' => 5, 'stage_label' => '34 kg - 10 reps'],
            ['skill_id' => 3, 'skill_name' => 'Snatch', 'stage' => 6, 'stage_label' => '42 kg - 6 reps'],
            ['skill_id' => 3, 'skill_name' => 'Snatch', 'stage' => 7, 'stage_label' => '49 kg - 3 reps'],
            ['skill_id' => 3, 'skill_name' => 'Snatch', 'stage' => 8, 'stage_label' => '46 kg - 7 reps'],
            ['skill_id' => 3, 'skill_name' => 'Snatch', 'stage' => 9, 'stage_label' => '52 kg - 5 reps'],
            ['skill_id' => 3, 'skill_name' => 'Snatch', 'stage' => 10, 'stage_label' => '48 kg - 9 reps'],
            ['skill_id' => 3, 'skill_name' => 'Snatch', 'stage' => 11, 'stage_label' => '55 kg - 6 reps'],
            ['skill_id' => 3, 'skill_name' => 'Snatch', 'stage' => 12, 'stage_label' => '53 kg - 9 reps'],
            ['skill_id' => 3, 'skill_name' => 'Snatch', 'stage' => 13, 'stage_label' => '63 kg - 5 reps'],
            ['skill_id' => 3, 'skill_name' => 'Snatch', 'stage' => 14, 'stage_label' => '68 kg - 4 reps'],
            ['skill_id' => 3, 'skill_name' => 'Snatch', 'stage' => 15, 'stage_label' => '56 kg - 11 reps'],
            ['skill_id' => 3, 'skill_name' => 'Snatch', 'stage' => 16, 'stage_label' => '66 kg - 7 reps'],
            ['skill_id' => 3, 'skill_name' => 'Snatch', 'stage' => 17, 'stage_label' => '77 kg - 4 reps'],
            ['skill_id' => 3, 'skill_name' => 'Snatch', 'stage' => 18, 'stage_label' => '70 kg - 8 reps'],
            ['skill_id' => 3, 'skill_name' => 'Snatch', 'stage' => 19, 'stage_label' => '77 kg - 6 reps'],
            ['skill_id' => 3, 'skill_name' => 'Snatch', 'stage' => 20, 'stage_label' => '70 kg - 10 reps'],
            ['skill_id' => 4, 'skill_name' => 'Clean & Jerk', 'stage' => 1, 'stage_label' => '29 kg - 5 reps'],
            ['skill_id' => 4, 'skill_name' => 'Clean & Jerk', 'stage' => 2, 'stage_label' => '30 kg - 8 reps'],
            ['skill_id' => 4, 'skill_name' => 'Clean & Jerk', 'stage' => 3, 'stage_label' => '38 kg - 4 reps'],
            ['skill_id' => 4, 'skill_name' => 'Clean & Jerk', 'stage' => 4, 'stage_label' => '43 kg - 3 reps'],
            ['skill_id' => 4, 'skill_name' => 'Clean & Jerk', 'stage' => 5, 'stage_label' => '37 kg - 10 reps'],
            ['skill_id' => 4, 'skill_name' => 'Clean & Jerk', 'stage' => 6, 'stage_label' => '46 kg - 6 reps'],
            ['skill_id' => 4, 'skill_name' => 'Clean & Jerk', 'stage' => 7, 'stage_label' => '55 kg - 3 reps'],
            ['skill_id' => 4, 'skill_name' => 'Clean & Jerk', 'stage' => 8, 'stage_label' => '52 kg - 7 reps'],
            ['skill_id' => 4, 'skill_name' => 'Clean & Jerk', 'stage' => 9, 'stage_label' => '59 kg - 5 reps'],
            ['skill_id' => 4, 'skill_name' => 'Clean & Jerk', 'stage' => 10, 'stage_label' => '55 kg - 9 reps'],
            ['skill_id' => 4, 'skill_name' => 'Clean & Jerk', 'stage' => 11, 'stage_label' => '64 kg - 6 reps'],
            ['skill_id' => 4, 'skill_name' => 'Clean & Jerk', 'stage' => 12, 'stage_label' => '62 kg - 9 reps'],
            ['skill_id' => 4, 'skill_name' => 'Clean & Jerk', 'stage' => 13, 'stage_label' => '74 kg - 5 reps'],
            ['skill_id' => 4, 'skill_name' => 'Clean & Jerk', 'stage' => 14, 'stage_label' => '81 kg - 4 reps'],
            ['skill_id' => 4, 'skill_name' => 'Clean & Jerk', 'stage' => 15, 'stage_label' => '67 kg - 11 reps'],
            ['skill_id' => 4, 'skill_name' => 'Clean & Jerk', 'stage' => 16, 'stage_label' => '80 kg - 7 reps'],
            ['skill_id' => 4, 'skill_name' => 'Clean & Jerk', 'stage' => 17, 'stage_label' => '92 kg - 4 reps'],
            ['skill_id' => 4, 'skill_name' => 'Clean & Jerk', 'stage' => 18, 'stage_label' => '84 kg - 8 reps'],
            ['skill_id' => 4, 'skill_name' => 'Clean & Jerk', 'stage' => 19, 'stage_label' => '93 kg - 6 reps'],
            ['skill_id' => 4, 'skill_name' => 'Clean & Jerk', 'stage' => 20, 'stage_label' => '85 kg - 10 reps'],
            ['skill_id' => 5, 'skill_name' => 'Clean', 'stage' => 1, 'stage_label' => '35 kg - 5 reps'],
            ['skill_id' => 5, 'skill_name' => 'Clean', 'stage' => 2, 'stage_label' => '36 kg - 8 reps'],
            ['skill_id' => 5, 'skill_name' => 'Clean', 'stage' => 3, 'stage_label' => '45 kg - 4 reps'],
            ['skill_id' => 5, 'skill_name' => 'Clean', 'stage' => 4, 'stage_label' => '51 kg - 3 reps'],
            ['skill_id' => 5, 'skill_name' => 'Clean', 'stage' => 5, 'stage_label' => '44 kg - 10 reps'],
            ['skill_id' => 5, 'skill_name' => 'Clean', 'stage' => 6, 'stage_label' => '55 kg - 6 reps'],
            ['skill_id' => 5, 'skill_name' => 'Clean', 'stage' => 7, 'stage_label' => '65 kg - 3 reps'],
            ['skill_id' => 5, 'skill_name' => 'Clean', 'stage' => 8, 'stage_label' => '61 kg - 7 reps'],
            ['skill_id' => 5, 'skill_name' => 'Clean', 'stage' => 9, 'stage_label' => '70 kg - 5 reps'],
            ['skill_id' => 5, 'skill_name' => 'Clean', 'stage' => 10, 'stage_label' => '65 kg - 9 reps'],
            ['skill_id' => 5, 'skill_name' => 'Clean', 'stage' => 11, 'stage_label' => '76 kg - 6 reps'],
            ['skill_id' => 5, 'skill_name' => 'Clean', 'stage' => 12, 'stage_label' => '73 kg - 9 reps'],
            ['skill_id' => 5, 'skill_name' => 'Clean', 'stage' => 13, 'stage_label' => '88 kg - 5 reps'],
            ['skill_id' => 5, 'skill_name' => 'Clean', 'stage' => 14, 'stage_label' => '95 kg - 4 reps'],
            ['skill_id' => 5, 'skill_name' => 'Clean', 'stage' => 15, 'stage_label' => '79 kg - 11 reps'],
            ['skill_id' => 5, 'skill_name' => 'Clean', 'stage' => 16, 'stage_label' => '94 kg - 7 reps'],
            ['skill_id' => 5, 'skill_name' => 'Clean', 'stage' => 17, 'stage_label' => '109 kg - 4 reps'],
            ['skill_id' => 5, 'skill_name' => 'Clean', 'stage' => 18, 'stage_label' => '100 kg - 8 reps'],
            ['skill_id' => 5, 'skill_name' => 'Clean', 'stage' => 19, 'stage_label' => '110 kg - 6 reps'],
            ['skill_id' => 5, 'skill_name' => 'Clean', 'stage' => 20, 'stage_label' => '100 kg - 10 reps'],
            ['skill_id' => 6, 'skill_name' => 'Deadlift', 'stage' => 1, 'stage_label' => '59 kg - 5 reps'],
            ['skill_id' => 6, 'skill_name' => 'Deadlift', 'stage' => 2, 'stage_label' => '59 kg - 8 reps'],
            ['skill_id' => 6, 'skill_name' => 'Deadlift', 'stage' => 3, 'stage_label' => '72 kg - 4 reps'],
            ['skill_id' => 6, 'skill_name' => 'Deadlift', 'stage' => 4, 'stage_label' => '80 kg - 3 reps'],
            ['skill_id' => 6, 'skill_name' => 'Deadlift', 'stage' => 5, 'stage_label' => '68 kg - 10 reps'],
            ['skill_id' => 6, 'skill_name' => 'Deadlift', 'stage' => 6, 'stage_label' => '84 kg - 6 reps'],
            ['skill_id' => 6, 'skill_name' => 'Deadlift', 'stage' => 7, 'stage_label' => '98 kg - 3 reps'],
            ['skill_id' => 6, 'skill_name' => 'Deadlift', 'stage' => 8, 'stage_label' => '92 kg - 7 reps'],
            ['skill_id' => 6, 'skill_name' => 'Deadlift', 'stage' => 9, 'stage_label' => '104 kg - 5 reps'],
            ['skill_id' => 6, 'skill_name' => 'Deadlift', 'stage' => 10, 'stage_label' => '96 kg - 9 reps'],
            ['skill_id' => 6, 'skill_name' => 'Deadlift', 'stage' => 11, 'stage_label' => '111 kg - 6 reps'],
            ['skill_id' => 6, 'skill_name' => 'Deadlift', 'stage' => 12, 'stage_label' => '106 kg - 9 reps'],
            ['skill_id' => 6, 'skill_name' => 'Deadlift', 'stage' => 13, 'stage_label' => '126 kg - 5 reps'],
            ['skill_id' => 6, 'skill_name' => 'Deadlift', 'stage' => 14, 'stage_label' => '136 kg - 4 reps'],
            ['skill_id' => 6, 'skill_name' => 'Deadlift', 'stage' => 15, 'stage_label' => '113 kg - 11 reps'],
            ['skill_id' => 6, 'skill_name' => 'Deadlift', 'stage' => 16, 'stage_label' => '133 kg - 7 reps'],
            ['skill_id' => 6, 'skill_name' => 'Deadlift', 'stage' => 17, 'stage_label' => '154 kg - 4 reps'],
            ['skill_id' => 6, 'skill_name' => 'Deadlift', 'stage' => 18, 'stage_label' => '140 kg - 8 reps'],
            ['skill_id' => 6, 'skill_name' => 'Deadlift', 'stage' => 19, 'stage_label' => '155 kg - 6 reps'],
            ['skill_id' => 6, 'skill_name' => 'Deadlift', 'stage' => 20, 'stage_label' => '140 kg - 10 reps'],
            ['skill_id' => 7, 'skill_name' => 'Front Squat', 'stage' => 1, 'stage_label' => '35 kg - 5 reps'],
            ['skill_id' => 7, 'skill_name' => 'Front Squat', 'stage' => 2, 'stage_label' => '36 kg - 8 reps'],
            ['skill_id' => 7, 'skill_name' => 'Front Squat', 'stage' => 3, 'stage_label' => '45 kg - 4 reps'],
            ['skill_id' => 7, 'skill_name' => 'Front Squat', 'stage' => 4, 'stage_label' => '51 kg - 3 reps'],
            ['skill_id' => 7, 'skill_name' => 'Front Squat', 'stage' => 5, 'stage_label' => '44 kg - 10 reps'],
            ['skill_id' => 7, 'skill_name' => 'Front Squat', 'stage' => 6, 'stage_label' => '55 kg - 6 reps'],
            ['skill_id' => 7, 'skill_name' => 'Front Squat', 'stage' => 7, 'stage_label' => '65 kg - 3 reps'],
            ['skill_id' => 7, 'skill_name' => 'Front Squat', 'stage' => 8, 'stage_label' => '61 kg - 7 reps'],
            ['skill_id' => 7, 'skill_name' => 'Front Squat', 'stage' => 9, 'stage_label' => '70 kg - 5 reps'],
            ['skill_id' => 7, 'skill_name' => 'Front Squat', 'stage' => 10, 'stage_label' => '65 kg - 9 reps'],
            ['skill_id' => 7, 'skill_name' => 'Front Squat', 'stage' => 11, 'stage_label' => '76 kg - 6 reps'],
            ['skill_id' => 7, 'skill_name' => 'Front Squat', 'stage' => 12, 'stage_label' => '73 kg - 9 reps'],
            ['skill_id' => 7, 'skill_name' => 'Front Squat', 'stage' => 13, 'stage_label' => '88 kg - 5 reps'],
            ['skill_id' => 7, 'skill_name' => 'Front Squat', 'stage' => 14, 'stage_label' => '95 kg - 4 reps'],
            ['skill_id' => 7, 'skill_name' => 'Front Squat', 'stage' => 15, 'stage_label' => '79 kg - 11 reps'],
            ['skill_id' => 7, 'skill_name' => 'Front Squat', 'stage' => 16, 'stage_label' => '94 kg - 7 reps'],
            ['skill_id' => 7, 'skill_name' => 'Front Squat', 'stage' => 17, 'stage_label' => '109 kg - 4 reps'],
            ['skill_id' => 7, 'skill_name' => 'Front Squat', 'stage' => 18, 'stage_label' => '100 kg - 8 reps'],
            ['skill_id' => 7, 'skill_name' => 'Front Squat', 'stage' => 19, 'stage_label' => '110 kg - 6 reps'],
            ['skill_id' => 7, 'skill_name' => 'Front Squat', 'stage' => 20, 'stage_label' => '100 kg - 10 reps'],
            ['skill_id' => 8, 'skill_name' => 'Back Squat', 'stage' => 1, 'stage_label' => '47 kg - 5 reps'],
            ['skill_id' => 8, 'skill_name' => 'Back Squat', 'stage' => 2, 'stage_label' => '47 kg - 8 reps'],
            ['skill_id' => 8, 'skill_name' => 'Back Squat', 'stage' => 3, 'stage_label' => '59 kg - 4 reps'],
            ['skill_id' => 8, 'skill_name' => 'Back Squat', 'stage' => 4, 'stage_label' => '65 kg - 3 reps'],
            ['skill_id' => 8, 'skill_name' => 'Back Squat', 'stage' => 5, 'stage_label' => '56 kg - 10 reps'],
            ['skill_id' => 8, 'skill_name' => 'Back Squat', 'stage' => 6, 'stage_label' => '70 kg - 6 reps'],
            ['skill_id' => 8, 'skill_name' => 'Back Squat', 'stage' => 7, 'stage_label' => '81 kg - 3 reps'],
            ['skill_id' => 8, 'skill_name' => 'Back Squat', 'stage' => 8, 'stage_label' => '76 kg - 7 reps'],
            ['skill_id' => 8, 'skill_name' => 'Back Squat', 'stage' => 9, 'stage_label' => '87 kg - 5 reps'],
            ['skill_id' => 8, 'skill_name' => 'Back Squat', 'stage' => 10, 'stage_label' => '81 kg - 9 reps'],
            ['skill_id' => 8, 'skill_name' => 'Back Squat', 'stage' => 11, 'stage_label' => '94 kg - 6 reps'],
            ['skill_id' => 8, 'skill_name' => 'Back Squat', 'stage' => 12, 'stage_label' => '89 kg - 9 reps'],
            ['skill_id' => 8, 'skill_name' => 'Back Squat', 'stage' => 13, 'stage_label' => '107 kg - 5 reps'],
            ['skill_id' => 8, 'skill_name' => 'Back Squat', 'stage' => 14, 'stage_label' => '116 kg - 4 reps'],
            ['skill_id' => 8, 'skill_name' => 'Back Squat', 'stage' => 15, 'stage_label' => '96 kg - 11 reps'],
            ['skill_id' => 8, 'skill_name' => 'Back Squat', 'stage' => 16, 'stage_label' => '114 kg - 7 reps'],
            ['skill_id' => 8, 'skill_name' => 'Back Squat', 'stage' => 17, 'stage_label' => '131 kg - 4 reps'],
            ['skill_id' => 8, 'skill_name' => 'Back Squat', 'stage' => 18, 'stage_label' => '120 kg - 8 reps'],
            ['skill_id' => 8, 'skill_name' => 'Back Squat', 'stage' => 19, 'stage_label' => '132 kg - 6 reps'],
            ['skill_id' => 8, 'skill_name' => 'Back Squat', 'stage' => 20, 'stage_label' => '120 kg - 10 reps'],
            ['skill_id' => 9, 'skill_name' => 'Overhead Squat', 'stage' => 1, 'stage_label' => '23 kg - 5 reps'],
            ['skill_id' => 9, 'skill_name' => 'Overhead Squat', 'stage' => 2, 'stage_label' => '24 kg - 8 reps'],
            ['skill_id' => 9, 'skill_name' => 'Overhead Squat', 'stage' => 3, 'stage_label' => '30 kg - 4 reps'],
            ['skill_id' => 9, 'skill_name' => 'Overhead Squat', 'stage' => 4, 'stage_label' => '34 kg - 3 reps'],
            ['skill_id' => 9, 'skill_name' => 'Overhead Squat', 'stage' => 5, 'stage_label' => '30 kg - 10 reps'],
            ['skill_id' => 9, 'skill_name' => 'Overhead Squat', 'stage' => 6, 'stage_label' => '38 kg - 6 reps'],
            ['skill_id' => 9, 'skill_name' => 'Overhead Squat', 'stage' => 7, 'stage_label' => '44 kg - 3 reps'],
            ['skill_id' => 9, 'skill_name' => 'Overhead Squat', 'stage' => 8, 'stage_label' => '42 kg - 7 reps'],
            ['skill_id' => 9, 'skill_name' => 'Overhead Squat', 'stage' => 9, 'stage_label' => '48 kg - 5 reps'],
            ['skill_id' => 9, 'skill_name' => 'Overhead Squat', 'stage' => 10, 'stage_label' => '45 kg - 9 reps'],
            ['skill_id' => 9, 'skill_name' => 'Overhead Squat', 'stage' => 11, 'stage_label' => '53 kg - 6 reps'],
            ['skill_id' => 9, 'skill_name' => 'Overhead Squat', 'stage' => 12, 'stage_label' => '50 kg - 9 reps'],
            ['skill_id' => 9, 'skill_name' => 'Overhead Squat', 'stage' => 13, 'stage_label' => '61 kg - 5 reps'],
            ['skill_id' => 9, 'skill_name' => 'Overhead Squat', 'stage' => 14, 'stage_label' => '66 kg - 4 reps'],
            ['skill_id' => 9, 'skill_name' => 'Overhead Squat', 'stage' => 15, 'stage_label' => '55 kg - 11 reps'],
            ['skill_id' => 9, 'skill_name' => 'Overhead Squat', 'stage' => 16, 'stage_label' => '65 kg - 7 reps'],
            ['skill_id' => 9, 'skill_name' => 'Overhead Squat', 'stage' => 17, 'stage_label' => '76 kg - 4 reps'],
            ['skill_id' => 9, 'skill_name' => 'Overhead Squat', 'stage' => 18, 'stage_label' => '69 kg - 8 reps'],
            ['skill_id' => 9, 'skill_name' => 'Overhead Squat', 'stage' => 19, 'stage_label' => '77 kg - 6 reps'],
            ['skill_id' => 9, 'skill_name' => 'Overhead Squat', 'stage' => 20, 'stage_label' => '70 kg - 10 reps'],
            ['skill_id' => 10, 'skill_name' => 'Pull up', 'stage' => 1, 'stage_label' => '1 reps'],
            ['skill_id' => 10, 'skill_name' => 'Pull up', 'stage' => 2, 'stage_label' => '3 reps'],
            ['skill_id' => 10, 'skill_name' => 'Pull up', 'stage' => 3, 'stage_label' => '5 reps'],
            ['skill_id' => 10, 'skill_name' => 'Pull up', 'stage' => 4, 'stage_label' => '7 reps'],
            ['skill_id' => 10, 'skill_name' => 'Pull up', 'stage' => 5, 'stage_label' => '9 reps'],
            ['skill_id' => 10, 'skill_name' => 'Pull up', 'stage' => 6, 'stage_label' => '11 reps'],
            ['skill_id' => 10, 'skill_name' => 'Pull up', 'stage' => 7, 'stage_label' => '13 reps'],
            ['skill_id' => 10, 'skill_name' => 'Pull up', 'stage' => 8, 'stage_label' => '15 reps'],
            ['skill_id' => 10, 'skill_name' => 'Pull up', 'stage' => 9, 'stage_label' => '17 reps'],
            ['skill_id' => 10, 'skill_name' => 'Pull up', 'stage' => 10, 'stage_label' => '19 reps'],
            ['skill_id' => 10, 'skill_name' => 'Pull up', 'stage' => 11, 'stage_label' => '22 reps'],
            ['skill_id' => 10, 'skill_name' => 'Pull up', 'stage' => 12, 'stage_label' => '24 reps'],
            ['skill_id' => 10, 'skill_name' => 'Pull up', 'stage' => 13, 'stage_label' => '26 reps'],
            ['skill_id' => 10, 'skill_name' => 'Pull up', 'stage' => 14, 'stage_label' => '28 reps'],
            ['skill_id' => 10, 'skill_name' => 'Pull up', 'stage' => 15, 'stage_label' => '30 reps'],
            ['skill_id' => 10, 'skill_name' => 'Pull up', 'stage' => 16, 'stage_label' => '32 reps'],
            ['skill_id' => 10, 'skill_name' => 'Pull up', 'stage' => 17, 'stage_label' => '34 reps'],
            ['skill_id' => 10, 'skill_name' => 'Pull up', 'stage' => 18, 'stage_label' => '36 reps'],
            ['skill_id' => 10, 'skill_name' => 'Pull up', 'stage' => 19, 'stage_label' => '38 reps'],
            ['skill_id' => 10, 'skill_name' => 'Pull up', 'stage' => 20, 'stage_label' => '40 reps'],
            ['skill_id' => 11, 'skill_name' => 'Push up', 'stage' => 1, 'stage_label' => '1 reps'],
            ['skill_id' => 11, 'skill_name' => 'Push up', 'stage' => 2, 'stage_label' => '3 reps'],
            ['skill_id' => 11, 'skill_name' => 'Push up', 'stage' => 3, 'stage_label' => '4 reps'],
            ['skill_id' => 11, 'skill_name' => 'Push up', 'stage' => 4, 'stage_label' => '6 reps'],
            ['skill_id' => 11, 'skill_name' => 'Push up', 'stage' => 5, 'stage_label' => '7 reps'],
            ['skill_id' => 11, 'skill_name' => 'Push up', 'stage' => 6, 'stage_label' => '9 reps'],
            ['skill_id' => 11, 'skill_name' => 'Push up', 'stage' => 7, 'stage_label' => '10 reps'],
            ['skill_id' => 11, 'skill_name' => 'Push up', 'stage' => 8, 'stage_label' => '12 reps'],
            ['skill_id' => 11, 'skill_name' => 'Push up', 'stage' => 9, 'stage_label' => '13 reps'],
            ['skill_id' => 11, 'skill_name' => 'Push up', 'stage' => 10, 'stage_label' => '15 reps'],
            ['skill_id' => 11, 'skill_name' => 'Push up', 'stage' => 11, 'stage_label' => '16 reps'],
            ['skill_id' => 11, 'skill_name' => 'Push up', 'stage' => 12, 'stage_label' => '18 reps'],
            ['skill_id' => 11, 'skill_name' => 'Push up', 'stage' => 13, 'stage_label' => '19 reps'],
            ['skill_id' => 11, 'skill_name' => 'Push up', 'stage' => 14, 'stage_label' => '21 reps'],
            ['skill_id' => 11, 'skill_name' => 'Push up', 'stage' => 15, 'stage_label' => '22 reps'],
            ['skill_id' => 11, 'skill_name' => 'Push up', 'stage' => 16, 'stage_label' => '24 reps'],
            ['skill_id' => 11, 'skill_name' => 'Push up', 'stage' => 17, 'stage_label' => '25 reps'],
            ['skill_id' => 11, 'skill_name' => 'Push up', 'stage' => 18, 'stage_label' => '27 reps'],
            ['skill_id' => 11, 'skill_name' => 'Push up', 'stage' => 19, 'stage_label' => '28 reps'],
            ['skill_id' => 11, 'skill_name' => 'Push up', 'stage' => 20, 'stage_label' => '30 reps'],
            ['skill_id' => 12, 'skill_name' => 'Toes to bar', 'stage' => 1, 'stage_label' => '1 reps'],
            ['skill_id' => 12, 'skill_name' => 'Toes to bar', 'stage' => 2, 'stage_label' => '4 reps'],
            ['skill_id' => 12, 'skill_name' => 'Toes to bar', 'stage' => 3, 'stage_label' => '6 reps'],
            ['skill_id' => 12, 'skill_name' => 'Toes to bar', 'stage' => 4, 'stage_label' => '9 reps'],
            ['skill_id' => 12, 'skill_name' => 'Toes to bar', 'stage' => 5, 'stage_label' => '11 reps'],
            ['skill_id' => 12, 'skill_name' => 'Toes to bar', 'stage' => 6, 'stage_label' => '14 reps'],
            ['skill_id' => 12, 'skill_name' => 'Toes to bar', 'stage' => 7, 'stage_label' => '16 reps'],
            ['skill_id' => 12, 'skill_name' => 'Toes to bar', 'stage' => 8, 'stage_label' => '19 reps'],
            ['skill_id' => 12, 'skill_name' => 'Toes to bar', 'stage' => 9, 'stage_label' => '22 reps'],
            ['skill_id' => 12, 'skill_name' => 'Toes to bar', 'stage' => 10, 'stage_label' => '24 reps'],
            ['skill_id' => 12, 'skill_name' => 'Toes to bar', 'stage' => 11, 'stage_label' => '27 reps'],
            ['skill_id' => 12, 'skill_name' => 'Toes to bar', 'stage' => 12, 'stage_label' => '29 reps'],
            ['skill_id' => 12, 'skill_name' => 'Toes to bar', 'stage' => 13, 'stage_label' => '32 reps'],
            ['skill_id' => 12, 'skill_name' => 'Toes to bar', 'stage' => 14, 'stage_label' => '35 reps'],
            ['skill_id' => 12, 'skill_name' => 'Toes to bar', 'stage' => 15, 'stage_label' => '37 reps'],
            ['skill_id' => 12, 'skill_name' => 'Toes to bar', 'stage' => 16, 'stage_label' => '40 reps'],
            ['skill_id' => 12, 'skill_name' => 'Toes to bar', 'stage' => 17, 'stage_label' => '42 reps'],
            ['skill_id' => 12, 'skill_name' => 'Toes to bar', 'stage' => 18, 'stage_label' => '45 reps'],
            ['skill_id' => 12, 'skill_name' => 'Toes to bar', 'stage' => 19, 'stage_label' => '47 reps'],
            ['skill_id' => 12, 'skill_name' => 'Toes to bar', 'stage' => 20, 'stage_label' => '50 reps'],
            ['skill_id' => 13, 'skill_name' => 'Handstand Push up', 'stage' => 1, 'stage_label' => '1 reps'],
            ['skill_id' => 13, 'skill_name' => 'Handstand Push up', 'stage' => 2, 'stage_label' => '4 reps'],
            ['skill_id' => 13, 'skill_name' => 'Handstand Push up', 'stage' => 3, 'stage_label' => '6 reps'],
            ['skill_id' => 13, 'skill_name' => 'Handstand Push up', 'stage' => 4, 'stage_label' => '9 reps'],
            ['skill_id' => 13, 'skill_name' => 'Handstand Push up', 'stage' => 5, 'stage_label' => '11 reps'],
            ['skill_id' => 13, 'skill_name' => 'Handstand Push up', 'stage' => 6, 'stage_label' => '14 reps'],
            ['skill_id' => 13, 'skill_name' => 'Handstand Push up', 'stage' => 7, 'stage_label' => '16 reps'],
            ['skill_id' => 13, 'skill_name' => 'Handstand Push up', 'stage' => 8, 'stage_label' => '19 reps'],
            ['skill_id' => 13, 'skill_name' => 'Handstand Push up', 'stage' => 9, 'stage_label' => '22 reps'],
            ['skill_id' => 13, 'skill_name' => 'Handstand Push up', 'stage' => 10, 'stage_label' => '24 reps'],
            ['skill_id' => 13, 'skill_name' => 'Handstand Push up', 'stage' => 11, 'stage_label' => '27 reps'],
            ['skill_id' => 13, 'skill_name' => 'Handstand Push up', 'stage' => 12, 'stage_label' => '29 reps'],
            ['skill_id' => 13, 'skill_name' => 'Handstand Push up', 'stage' => 13, 'stage_label' => '32 reps'],
            ['skill_id' => 13, 'skill_name' => 'Handstand Push up', 'stage' => 14, 'stage_label' => '35 reps'],
            ['skill_id' => 13, 'skill_name' => 'Handstand Push up', 'stage' => 15, 'stage_label' => '37 reps'],
            ['skill_id' => 13, 'skill_name' => 'Handstand Push up', 'stage' => 16, 'stage_label' => '40 reps'],
            ['skill_id' => 13, 'skill_name' => 'Handstand Push up', 'stage' => 17, 'stage_label' => '42 reps'],
            ['skill_id' => 13, 'skill_name' => 'Handstand Push up', 'stage' => 18, 'stage_label' => '45 reps'],
            ['skill_id' => 13, 'skill_name' => 'Handstand Push up', 'stage' => 19, 'stage_label' => '47 reps'],
            ['skill_id' => 13, 'skill_name' => 'Handstand Push up', 'stage' => 20, 'stage_label' => '50 reps'],
            ['skill_id' => 14, 'skill_name' => 'Bar MU', 'stage' => 1, 'stage_label' => '1 reps'],
            ['skill_id' => 14, 'skill_name' => 'Bar MU', 'stage' => 2, 'stage_label' => '2 reps'],
            ['skill_id' => 14, 'skill_name' => 'Bar MU', 'stage' => 3, 'stage_label' => '3 reps'],
            ['skill_id' => 14, 'skill_name' => 'Bar MU', 'stage' => 4, 'stage_label' => '4 reps'],
            ['skill_id' => 14, 'skill_name' => 'Bar MU', 'stage' => 5, 'stage_label' => '5 reps'],
            ['skill_id' => 14, 'skill_name' => 'Bar MU', 'stage' => 6, 'stage_label' => '6 reps'],
            ['skill_id' => 14, 'skill_name' => 'Bar MU', 'stage' => 7, 'stage_label' => '7 reps'],
            ['skill_id' => 14, 'skill_name' => 'Bar MU', 'stage' => 8, 'stage_label' => '8 reps'],
            ['skill_id' => 14, 'skill_name' => 'Bar MU', 'stage' => 9, 'stage_label' => '9 reps'],
            ['skill_id' => 14, 'skill_name' => 'Bar MU', 'stage' => 10, 'stage_label' => '10 reps'],
            ['skill_id' => 14, 'skill_name' => 'Bar MU', 'stage' => 11, 'stage_label' => '11 reps'],
            ['skill_id' => 14, 'skill_name' => 'Bar MU', 'stage' => 12, 'stage_label' => '12 reps'],
            ['skill_id' => 14, 'skill_name' => 'Bar MU', 'stage' => 13, 'stage_label' => '13 reps'],
            ['skill_id' => 14, 'skill_name' => 'Bar MU', 'stage' => 14, 'stage_label' => '14 reps'],
            ['skill_id' => 14, 'skill_name' => 'Bar MU', 'stage' => 15, 'stage_label' => '15 reps'],
            ['skill_id' => 14, 'skill_name' => 'Bar MU', 'stage' => 16, 'stage_label' => '16 reps'],
            ['skill_id' => 14, 'skill_name' => 'Bar MU', 'stage' => 17, 'stage_label' => '17 reps'],
            ['skill_id' => 14, 'skill_name' => 'Bar MU', 'stage' => 18, 'stage_label' => '18 reps'],
            ['skill_id' => 14, 'skill_name' => 'Bar MU', 'stage' => 19, 'stage_label' => '19 reps'],
            ['skill_id' => 14, 'skill_name' => 'Bar MU', 'stage' => 20, 'stage_label' => '20 reps'],
            ['skill_id' => 15, 'skill_name' => 'Ring MU', 'stage' => 1, 'stage_label' => '1 reps'],
            ['skill_id' => 15, 'skill_name' => 'Ring MU', 'stage' => 2, 'stage_label' => '2 reps'],
            ['skill_id' => 15, 'skill_name' => 'Ring MU', 'stage' => 3, 'stage_label' => '2 reps'],
            ['skill_id' => 15, 'skill_name' => 'Ring MU', 'stage' => 4, 'stage_label' => '3 reps'],
            ['skill_id' => 15, 'skill_name' => 'Ring MU', 'stage' => 5, 'stage_label' => '4 reps'],
            ['skill_id' => 15, 'skill_name' => 'Ring MU', 'stage' => 6, 'stage_label' => '5 reps'],
            ['skill_id' => 15, 'skill_name' => 'Ring MU', 'stage' => 7, 'stage_label' => '5 reps'],
            ['skill_id' => 15, 'skill_name' => 'Ring MU', 'stage' => 8, 'stage_label' => '6 reps'],
            ['skill_id' => 15, 'skill_name' => 'Ring MU', 'stage' => 9, 'stage_label' => '7 reps'],
            ['skill_id' => 15, 'skill_name' => 'Ring MU', 'stage' => 10, 'stage_label' => '8 reps'],
            ['skill_id' => 15, 'skill_name' => 'Ring MU', 'stage' => 11, 'stage_label' => '8 reps'],
            ['skill_id' => 15, 'skill_name' => 'Ring MU', 'stage' => 12, 'stage_label' => '9 reps'],
            ['skill_id' => 15, 'skill_name' => 'Ring MU', 'stage' => 13, 'stage_label' => '10 reps'],
            ['skill_id' => 15, 'skill_name' => 'Ring MU', 'stage' => 14, 'stage_label' => '11 reps'],
            ['skill_id' => 15, 'skill_name' => 'Ring MU', 'stage' => 15, 'stage_label' => '11 reps'],
            ['skill_id' => 15, 'skill_name' => 'Ring MU', 'stage' => 16, 'stage_label' => '12 reps'],
            ['skill_id' => 15, 'skill_name' => 'Ring MU', 'stage' => 17, 'stage_label' => '13 reps'],
            ['skill_id' => 15, 'skill_name' => 'Ring MU', 'stage' => 18, 'stage_label' => '14 reps'],
            ['skill_id' => 15, 'skill_name' => 'Ring MU', 'stage' => 19, 'stage_label' => '14 reps'],
            ['skill_id' => 15, 'skill_name' => 'Ring MU', 'stage' => 20, 'stage_label' => '15 reps'],
            ['skill_id' => 16, 'skill_name' => 'Chest to bar', 'stage' => 1, 'stage_label' => '1 reps'],
            ['skill_id' => 16, 'skill_name' => 'Chest to bar', 'stage' => 2, 'stage_label' => '2 reps'],
            ['skill_id' => 16, 'skill_name' => 'Chest to bar', 'stage' => 3, 'stage_label' => '4 reps'],
            ['skill_id' => 16, 'skill_name' => 'Chest to bar', 'stage' => 4, 'stage_label' => '5 reps'],
            ['skill_id' => 16, 'skill_name' => 'Chest to bar', 'stage' => 5, 'stage_label' => '6 reps'],
            ['skill_id' => 16, 'skill_name' => 'Chest to bar', 'stage' => 6, 'stage_label' => '7 reps'],
            ['skill_id' => 16, 'skill_name' => 'Chest to bar', 'stage' => 7, 'stage_label' => '9 reps'],
            ['skill_id' => 16, 'skill_name' => 'Chest to bar', 'stage' => 8, 'stage_label' => '10 reps'],
            ['skill_id' => 16, 'skill_name' => 'Chest to bar', 'stage' => 9, 'stage_label' => '11 reps'],
            ['skill_id' => 16, 'skill_name' => 'Chest to bar', 'stage' => 10, 'stage_label' => '12 reps'],
            ['skill_id' => 16, 'skill_name' => 'Chest to bar', 'stage' => 11, 'stage_label' => '14 reps'],
            ['skill_id' => 16, 'skill_name' => 'Chest to bar', 'stage' => 12, 'stage_label' => '15 reps'],
            ['skill_id' => 16, 'skill_name' => 'Chest to bar', 'stage' => 13, 'stage_label' => '16 reps'],
            ['skill_id' => 16, 'skill_name' => 'Chest to bar', 'stage' => 14, 'stage_label' => '17 reps'],
            ['skill_id' => 16, 'skill_name' => 'Chest to bar', 'stage' => 15, 'stage_label' => '19 reps'],
            ['skill_id' => 16, 'skill_name' => 'Chest to bar', 'stage' => 16, 'stage_label' => '20 reps'],
            ['skill_id' => 16, 'skill_name' => 'Chest to bar', 'stage' => 17, 'stage_label' => '21 reps'],
            ['skill_id' => 16, 'skill_name' => 'Chest to bar', 'stage' => 18, 'stage_label' => '22 reps'],
            ['skill_id' => 16, 'skill_name' => 'Chest to bar', 'stage' => 19, 'stage_label' => '24 reps'],
            ['skill_id' => 16, 'skill_name' => 'Chest to bar', 'stage' => 20, 'stage_label' => '25 reps'],
            ['skill_id' => 17, 'skill_name' => 'Pistol Squat', 'stage' => 1, 'stage_label' => '1 reps'],
            ['skill_id' => 17, 'skill_name' => 'Pistol Squat', 'stage' => 2, 'stage_label' => '3 reps'],
            ['skill_id' => 17, 'skill_name' => 'Pistol Squat', 'stage' => 3, 'stage_label' => '5 reps'],
            ['skill_id' => 17, 'skill_name' => 'Pistol Squat', 'stage' => 4, 'stage_label' => '7 reps'],
            ['skill_id' => 17, 'skill_name' => 'Pistol Squat', 'stage' => 5, 'stage_label' => '9 reps'],
            ['skill_id' => 17, 'skill_name' => 'Pistol Squat', 'stage' => 6, 'stage_label' => '11 reps'],
            ['skill_id' => 17, 'skill_name' => 'Pistol Squat', 'stage' => 7, 'stage_label' => '13 reps'],
            ['skill_id' => 17, 'skill_name' => 'Pistol Squat', 'stage' => 8, 'stage_label' => '15 reps'],
            ['skill_id' => 17, 'skill_name' => 'Pistol Squat', 'stage' => 9, 'stage_label' => '17 reps'],
            ['skill_id' => 17, 'skill_name' => 'Pistol Squat', 'stage' => 10, 'stage_label' => '19 reps'],
            ['skill_id' => 17, 'skill_name' => 'Pistol Squat', 'stage' => 11, 'stage_label' => '22 reps'],
            ['skill_id' => 17, 'skill_name' => 'Pistol Squat', 'stage' => 12, 'stage_label' => '24 reps'],
            ['skill_id' => 17, 'skill_name' => 'Pistol Squat', 'stage' => 13, 'stage_label' => '26 reps'],
            ['skill_id' => 17, 'skill_name' => 'Pistol Squat', 'stage' => 14, 'stage_label' => '28 reps'],
            ['skill_id' => 17, 'skill_name' => 'Pistol Squat', 'stage' => 15, 'stage_label' => '30 reps'],
            ['skill_id' => 17, 'skill_name' => 'Pistol Squat', 'stage' => 16, 'stage_label' => '32 reps'],
            ['skill_id' => 17, 'skill_name' => 'Pistol Squat', 'stage' => 17, 'stage_label' => '34 reps'],
            ['skill_id' => 17, 'skill_name' => 'Pistol Squat', 'stage' => 18, 'stage_label' => '36 reps'],
            ['skill_id' => 17, 'skill_name' => 'Pistol Squat', 'stage' => 19, 'stage_label' => '38 reps'],
            ['skill_id' => 17, 'skill_name' => 'Pistol Squat', 'stage' => 20, 'stage_label' => '40 reps'],
            ['skill_id' => 18, 'skill_name' => 'Handstand Walk', 'stage' => 1, 'stage_label' => '1 meters'],
            ['skill_id' => 18, 'skill_name' => 'Handstand Walk', 'stage' => 2, 'stage_label' => '2 meters'],
            ['skill_id' => 18, 'skill_name' => 'Handstand Walk', 'stage' => 3, 'stage_label' => '3 meters'],
            ['skill_id' => 18, 'skill_name' => 'Handstand Walk', 'stage' => 4, 'stage_label' => '4 meters'],
            ['skill_id' => 18, 'skill_name' => 'Handstand Walk', 'stage' => 5, 'stage_label' => '5 meters'],
            ['skill_id' => 18, 'skill_name' => 'Handstand Walk', 'stage' => 6, 'stage_label' => '6 meters'],
            ['skill_id' => 18, 'skill_name' => 'Handstand Walk', 'stage' => 7, 'stage_label' => '7 meters'],
            ['skill_id' => 18, 'skill_name' => 'Handstand Walk', 'stage' => 8, 'stage_label' => '8 meters'],
            ['skill_id' => 18, 'skill_name' => 'Handstand Walk', 'stage' => 9, 'stage_label' => '9 meters'],
            ['skill_id' => 18, 'skill_name' => 'Handstand Walk', 'stage' => 10, 'stage_label' => '10 meters'],
            ['skill_id' => 18, 'skill_name' => 'Handstand Walk', 'stage' => 11, 'stage_label' => '11 meters'],
            ['skill_id' => 18, 'skill_name' => 'Handstand Walk', 'stage' => 12, 'stage_label' => '12 meters'],
            ['skill_id' => 18, 'skill_name' => 'Handstand Walk', 'stage' => 13, 'stage_label' => '13 meters'],
            ['skill_id' => 18, 'skill_name' => 'Handstand Walk', 'stage' => 14, 'stage_label' => '14 meters'],
            ['skill_id' => 18, 'skill_name' => 'Handstand Walk', 'stage' => 15, 'stage_label' => '15 meters'],
            ['skill_id' => 18, 'skill_name' => 'Handstand Walk', 'stage' => 16, 'stage_label' => '16 meters'],
            ['skill_id' => 18, 'skill_name' => 'Handstand Walk', 'stage' => 17, 'stage_label' => '17 meters'],
            ['skill_id' => 18, 'skill_name' => 'Handstand Walk', 'stage' => 18, 'stage_label' => '18 meters'],
            ['skill_id' => 18, 'skill_name' => 'Handstand Walk', 'stage' => 19, 'stage_label' => '19 meters'],
            ['skill_id' => 18, 'skill_name' => 'Handstand Walk', 'stage' => 20, 'stage_label' => '20 meters'],
            ['skill_id' => 19, 'skill_name' => '5km Run', 'stage' => 1, 'stage_label' => '36 minutes'],
            ['skill_id' => 19, 'skill_name' => '5km Run', 'stage' => 2, 'stage_label' => '35 minutes'],
            ['skill_id' => 19, 'skill_name' => '5km Run', 'stage' => 3, 'stage_label' => '34 minutes'],
            ['skill_id' => 19, 'skill_name' => '5km Run', 'stage' => 4, 'stage_label' => '33 minutes'],
            ['skill_id' => 19, 'skill_name' => '5km Run', 'stage' => 5, 'stage_label' => '32 minutes'],
            ['skill_id' => 19, 'skill_name' => '5km Run', 'stage' => 6, 'stage_label' => '31 minutes'],
            ['skill_id' => 19, 'skill_name' => '5km Run', 'stage' => 7, 'stage_label' => '30 minutes'],
            ['skill_id' => 19, 'skill_name' => '5km Run', 'stage' => 8, 'stage_label' => '29 minutes'],
            ['skill_id' => 19, 'skill_name' => '5km Run', 'stage' => 9, 'stage_label' => '28 minutes'],
            ['skill_id' => 19, 'skill_name' => '5km Run', 'stage' => 10, 'stage_label' => '27 minutes'],
            ['skill_id' => 19, 'skill_name' => '5km Run', 'stage' => 11, 'stage_label' => '26 minutes'],
            ['skill_id' => 19, 'skill_name' => '5km Run', 'stage' => 12, 'stage_label' => '25 minutes'],
            ['skill_id' => 19, 'skill_name' => '5km Run', 'stage' => 13, 'stage_label' => '24 minutes'],
            ['skill_id' => 19, 'skill_name' => '5km Run', 'stage' => 14, 'stage_label' => '23 minutes'],
            ['skill_id' => 19, 'skill_name' => '5km Run', 'stage' => 15, 'stage_label' => '22 minutes'],
            ['skill_id' => 19, 'skill_name' => '5km Run', 'stage' => 16, 'stage_label' => '21 minutes'],
            ['skill_id' => 19, 'skill_name' => '5km Run', 'stage' => 17, 'stage_label' => '20 minutes'],
            ['skill_id' => 19, 'skill_name' => '5km Run', 'stage' => 18, 'stage_label' => '19 minutes'],
            ['skill_id' => 19, 'skill_name' => '5km Run', 'stage' => 19, 'stage_label' => '18 minutes'],
            ['skill_id' => 19, 'skill_name' => '5km Run', 'stage' => 20, 'stage_label' => '17 minutes'],
            ['skill_id' => 20, 'skill_name' => 'Row', 'stage' => 1, 'stage_label' => '2.5 minutes – 500m'],
            ['skill_id' => 20, 'skill_name' => 'Row', 'stage' => 2, 'stage_label' => '2.45 minutes – 500m'],
            ['skill_id' => 20, 'skill_name' => 'Row', 'stage' => 3, 'stage_label' => '2.39 minutes – 500m'],
            ['skill_id' => 20, 'skill_name' => 'Row', 'stage' => 4, 'stage_label' => '2.34 minutes – 500m'],
            ['skill_id' => 20, 'skill_name' => 'Row', 'stage' => 5, 'stage_label' => '2.29 minutes – 500m'],
            ['skill_id' => 20, 'skill_name' => 'Row', 'stage' => 6, 'stage_label' => '2.24 minutes – 500m'],
            ['skill_id' => 20, 'skill_name' => 'Row', 'stage' => 7, 'stage_label' => '2.18 minutes – 500m'],
            ['skill_id' => 20, 'skill_name' => 'Row', 'stage' => 8, 'stage_label' => '2.13 minutes – 500m'],
            ['skill_id' => 20, 'skill_name' => 'Row', 'stage' => 9, 'stage_label' => '2.08 minutes – 500m'],
            ['skill_id' => 20, 'skill_name' => 'Row', 'stage' => 10, 'stage_label' => '2.03 minutes – 500m'],
            ['skill_id' => 20, 'skill_name' => 'Row', 'stage' => 11, 'stage_label' => '1.97 minutes – 500m'],
            ['skill_id' => 20, 'skill_name' => 'Row', 'stage' => 12, 'stage_label' => '1.92 minutes – 500m'],
            ['skill_id' => 20, 'skill_name' => 'Row', 'stage' => 13, 'stage_label' => '1.87 minutes – 500m'],
            ['skill_id' => 20, 'skill_name' => 'Row', 'stage' => 14, 'stage_label' => '1.82 minutes – 500m'],
            ['skill_id' => 20, 'skill_name' => 'Row', 'stage' => 15, 'stage_label' => '1.76 minutes – 500m'],
            ['skill_id' => 20, 'skill_name' => 'Row', 'stage' => 16, 'stage_label' => '1.71 minutes – 500m'],
            ['skill_id' => 20, 'skill_name' => 'Row', 'stage' => 17, 'stage_label' => '1.66 minutes – 500m'],
            ['skill_id' => 20, 'skill_name' => 'Row', 'stage' => 18, 'stage_label' => '1.61 minutes – 500m'],
            ['skill_id' => 20, 'skill_name' => 'Row', 'stage' => 19, 'stage_label' => '1.55 minutes – 500m'],
            ['skill_id' => 20, 'skill_name' => 'Row', 'stage' => 20, 'stage_label' => '1.5 minutes – 500m'],
            ['skill_id' => 21, 'skill_name' => 'Bikerg', 'stage' => 1, 'stage_label' => '2.5 minutes – 1km'],
            ['skill_id' => 21, 'skill_name' => 'Bikerg', 'stage' => 2, 'stage_label' => '2.45 minutes – 1km'],
            ['skill_id' => 21, 'skill_name' => 'Bikerg', 'stage' => 3, 'stage_label' => '2.39 minutes – 1km'],
            ['skill_id' => 21, 'skill_name' => 'Bikerg', 'stage' => 4, 'stage_label' => '2.34 minutes – 1km'],
            ['skill_id' => 21, 'skill_name' => 'Bikerg', 'stage' => 5, 'stage_label' => '2.29 minutes – 1km'],
            ['skill_id' => 21, 'skill_name' => 'Bikerg', 'stage' => 6, 'stage_label' => '2.24 minutes – 1km'],
            ['skill_id' => 21, 'skill_name' => 'Bikerg', 'stage' => 7, 'stage_label' => '2.18 minutes – 1km'],
            ['skill_id' => 21, 'skill_name' => 'Bikerg', 'stage' => 8, 'stage_label' => '2.13 minutes – 1km'],
            ['skill_id' => 21, 'skill_name' => 'Bikerg', 'stage' => 9, 'stage_label' => '2.08 minutes – 1km'],
            ['skill_id' => 21, 'skill_name' => 'Bikerg', 'stage' => 10, 'stage_label' => '2.03 minutes – 1km'],
            ['skill_id' => 21, 'skill_name' => 'Bikerg', 'stage' => 11, 'stage_label' => '1.97 minutes – 1km'],
            ['skill_id' => 21, 'skill_name' => 'Bikerg', 'stage' => 12, 'stage_label' => '1.92 minutes – 1km'],
            ['skill_id' => 21, 'skill_name' => 'Bikerg', 'stage' => 13, 'stage_label' => '1.87 minutes – 1km'],
            ['skill_id' => 21, 'skill_name' => 'Bikerg', 'stage' => 14, 'stage_label' => '1.82 minutes – 1km'],
            ['skill_id' => 21, 'skill_name' => 'Bikerg', 'stage' => 15, 'stage_label' => '1.76 minutes – 1km'],
            ['skill_id' => 21, 'skill_name' => 'Bikerg', 'stage' => 16, 'stage_label' => '1.71 minutes – 1km'],
            ['skill_id' => 21, 'skill_name' => 'Bikerg', 'stage' => 17, 'stage_label' => '1.66 minutes – 1km'],
            ['skill_id' => 21, 'skill_name' => 'Bikerg', 'stage' => 18, 'stage_label' => '1.61 minutes – 1km'],
            ['skill_id' => 21, 'skill_name' => 'Bikerg', 'stage' => 19, 'stage_label' => '1.55 minutes – 1km'],
            ['skill_id' => 21, 'skill_name' => 'Bikerg', 'stage' => 20, 'stage_label' => '1.5 minutes – 1km'],
            ['skill_id' => 22, 'skill_name' => 'Skierg', 'stage' => 1, 'stage_label' => '2.5 minutes – 500m'],
            ['skill_id' => 22, 'skill_name' => 'Skierg', 'stage' => 2, 'stage_label' => '2.45 minutes – 500m'],
            ['skill_id' => 22, 'skill_name' => 'Skierg', 'stage' => 3, 'stage_label' => '2.39 minutes – 500m'],
            ['skill_id' => 22, 'skill_name' => 'Skierg', 'stage' => 4, 'stage_label' => '2.34 minutes – 500m'],
            ['skill_id' => 22, 'skill_name' => 'Skierg', 'stage' => 5, 'stage_label' => '2.29 minutes – 500m'],
            ['skill_id' => 22, 'skill_name' => 'Skierg', 'stage' => 6, 'stage_label' => '2.24 minutes – 500m'],
            ['skill_id' => 22, 'skill_name' => 'Skierg', 'stage' => 7, 'stage_label' => '2.18 minutes – 500m'],
            ['skill_id' => 22, 'skill_name' => 'Skierg', 'stage' => 8, 'stage_label' => '2.13 minutes – 500m'],
            ['skill_id' => 22, 'skill_name' => 'Skierg', 'stage' => 9, 'stage_label' => '2.08 minutes – 500m'],
            ['skill_id' => 22, 'skill_name' => 'Skierg', 'stage' => 10, 'stage_label' => '2.03 minutes – 500m'],
            ['skill_id' => 22, 'skill_name' => 'Skierg', 'stage' => 11, 'stage_label' => '1.97 minutes – 500m'],
            ['skill_id' => 22, 'skill_name' => 'Skierg', 'stage' => 12, 'stage_label' => '1.92 minutes – 500m'],
            ['skill_id' => 22, 'skill_name' => 'Skierg', 'stage' => 13, 'stage_label' => '1.87 minutes – 500m'],
            ['skill_id' => 22, 'skill_name' => 'Skierg', 'stage' => 14, 'stage_label' => '1.82 minutes – 500m'],
            ['skill_id' => 22, 'skill_name' => 'Skierg', 'stage' => 15, 'stage_label' => '1.76 minutes – 500m'],
            ['skill_id' => 22, 'skill_name' => 'Skierg', 'stage' => 16, 'stage_label' => '1.71 minutes – 500m'],
            ['skill_id' => 22, 'skill_name' => 'Skierg', 'stage' => 17, 'stage_label' => '1.66 minutes – 500m'],
            ['skill_id' => 22, 'skill_name' => 'Skierg', 'stage' => 18, 'stage_label' => '1.61 minutes – 500m'],
            ['skill_id' => 22, 'skill_name' => 'Skierg', 'stage' => 19, 'stage_label' => '1.55 minutes – 500m'],
            ['skill_id' => 22, 'skill_name' => 'Skierg', 'stage' => 20, 'stage_label' => '1.5 minutes – 500m'],
            ['skill_id' => 23, 'skill_name' => 'DU', 'stage' => 1, 'stage_label' => '1 reps in a row'],
            ['skill_id' => 23, 'skill_name' => 'DU', 'stage' => 2, 'stage_label' => '6 reps in a row'],
            ['skill_id' => 23, 'skill_name' => 'DU', 'stage' => 3, 'stage_label' => '11 reps in a row'],
            ['skill_id' => 23, 'skill_name' => 'DU', 'stage' => 4, 'stage_label' => '17 reps in a row'],
            ['skill_id' => 23, 'skill_name' => 'DU', 'stage' => 5, 'stage_label' => '22 reps in a row'],
            ['skill_id' => 23, 'skill_name' => 'DU', 'stage' => 6, 'stage_label' => '27 reps in a row'],
            ['skill_id' => 23, 'skill_name' => 'DU', 'stage' => 7, 'stage_label' => '32 reps in a row'],
            ['skill_id' => 23, 'skill_name' => 'DU', 'stage' => 8, 'stage_label' => '37 reps in a row'],
            ['skill_id' => 23, 'skill_name' => 'DU', 'stage' => 9, 'stage_label' => '43 reps in a row'],
            ['skill_id' => 23, 'skill_name' => 'DU', 'stage' => 10, 'stage_label' => '48 reps in a row'],
            ['skill_id' => 23, 'skill_name' => 'DU', 'stage' => 11, 'stage_label' => '53 reps in a row'],
            ['skill_id' => 23, 'skill_name' => 'DU', 'stage' => 12, 'stage_label' => '58 reps in a row'],
            ['skill_id' => 23, 'skill_name' => 'DU', 'stage' => 13, 'stage_label' => '64 reps in a row'],
            ['skill_id' => 23, 'skill_name' => 'DU', 'stage' => 14, 'stage_label' => '69 reps in a row'],
            ['skill_id' => 23, 'skill_name' => 'DU', 'stage' => 15, 'stage_label' => '74 reps in a row'],
            ['skill_id' => 23, 'skill_name' => 'DU', 'stage' => 16, 'stage_label' => '79 reps in a row'],
            ['skill_id' => 23, 'skill_name' => 'DU', 'stage' => 17, 'stage_label' => '84 reps in a row'],
            ['skill_id' => 23, 'skill_name' => 'DU', 'stage' => 18, 'stage_label' => '90 reps in a row'],
            ['skill_id' => 23, 'skill_name' => 'DU', 'stage' => 19, 'stage_label' => '95 reps in a row'],
            ['skill_id' => 23, 'skill_name' => 'DU', 'stage' => 20, 'stage_label' => '100 reps in a row'],
            ['skill_id' => 24, 'skill_name' => 'Burpees', 'stage' => 1, 'stage_label' => '5 reps under 1 minute'],
            ['skill_id' => 24, 'skill_name' => 'Burpees', 'stage' => 2, 'stage_label' => '6 reps under 1 minute'],
            ['skill_id' => 24, 'skill_name' => 'Burpees', 'stage' => 3, 'stage_label' => '8 reps under 1 minute'],
            ['skill_id' => 24, 'skill_name' => 'Burpees', 'stage' => 4, 'stage_label' => '9 reps under 1 minute'],
            ['skill_id' => 24, 'skill_name' => 'Burpees', 'stage' => 5, 'stage_label' => '10 reps under 1 minute'],
            ['skill_id' => 24, 'skill_name' => 'Burpees', 'stage' => 6, 'stage_label' => '12 reps under 1 minute'],
            ['skill_id' => 24, 'skill_name' => 'Burpees', 'stage' => 7, 'stage_label' => '13 reps under 1 minute'],
            ['skill_id' => 24, 'skill_name' => 'Burpees', 'stage' => 8, 'stage_label' => '14 reps under 1 minute'],
            ['skill_id' => 24, 'skill_name' => 'Burpees', 'stage' => 9, 'stage_label' => '16 reps under 1 minute'],
            ['skill_id' => 24, 'skill_name' => 'Burpees', 'stage' => 10, 'stage_label' => '17 reps under 1 minute'],
            ['skill_id' => 24, 'skill_name' => 'Burpees', 'stage' => 11, 'stage_label' => '18 reps under 1 minute'],
            ['skill_id' => 24, 'skill_name' => 'Burpees', 'stage' => 12, 'stage_label' => '19 reps under 1 minute'],
            ['skill_id' => 24, 'skill_name' => 'Burpees', 'stage' => 13, 'stage_label' => '21 reps under 1 minute'],
            ['skill_id' => 24, 'skill_name' => 'Burpees', 'stage' => 14, 'stage_label' => '22 reps under 1 minute'],
            ['skill_id' => 24, 'skill_name' => 'Burpees', 'stage' => 15, 'stage_label' => '23 reps under 1 minute'],
            ['skill_id' => 24, 'skill_name' => 'Burpees', 'stage' => 16, 'stage_label' => '25 reps under 1 minute'],
            ['skill_id' => 24, 'skill_name' => 'Burpees', 'stage' => 17, 'stage_label' => '26 reps under 1 minute'],
            ['skill_id' => 24, 'skill_name' => 'Burpees', 'stage' => 18, 'stage_label' => '27 reps under 1 minute'],
            ['skill_id' => 24, 'skill_name' => 'Burpees', 'stage' => 19, 'stage_label' => '29 reps under 1 minute'],
            ['skill_id' => 24, 'skill_name' => 'Burpees', 'stage' => 20, 'stage_label' => '30 reps under 1 minute'],
            ['skill_id' => 25, 'skill_name' => 'Box jumps over', 'stage' => 1, 'stage_label' => '5 reps under 1 minute'],
            ['skill_id' => 25, 'skill_name' => 'Box jumps over', 'stage' => 2, 'stage_label' => '7 reps under 1 minute'],
            ['skill_id' => 25, 'skill_name' => 'Box jumps over', 'stage' => 3, 'stage_label' => '10 reps under 1 minute'],
            ['skill_id' => 25, 'skill_name' => 'Box jumps over', 'stage' => 4, 'stage_label' => '12 reps under 1 minute'],
            ['skill_id' => 25, 'skill_name' => 'Box jumps over', 'stage' => 5, 'stage_label' => '14 reps under 1 minute'],
            ['skill_id' => 25, 'skill_name' => 'Box jumps over', 'stage' => 6, 'stage_label' => '17 reps under 1 minute'],
            ['skill_id' => 25, 'skill_name' => 'Box jumps over', 'stage' => 7, 'stage_label' => '19 reps under 1 minute'],
            ['skill_id' => 25, 'skill_name' => 'Box jumps over', 'stage' => 8, 'stage_label' => '22 reps under 1 minute'],
            ['skill_id' => 25, 'skill_name' => 'Box jumps over', 'stage' => 9, 'stage_label' => '24 reps under 1 minute'],
            ['skill_id' => 25, 'skill_name' => 'Box jumps over', 'stage' => 10, 'stage_label' => '26 reps under 1 minute'],
            ['skill_id' => 25, 'skill_name' => 'Box jumps over', 'stage' => 11, 'stage_label' => '29 reps under 1 minute'],
            ['skill_id' => 25, 'skill_name' => 'Box jumps over', 'stage' => 12, 'stage_label' => '31 reps under 1 minute'],
            ['skill_id' => 25, 'skill_name' => 'Box jumps over', 'stage' => 13, 'stage_label' => '33 reps under 1 minute'],
            ['skill_id' => 25, 'skill_name' => 'Box jumps over', 'stage' => 14, 'stage_label' => '36 reps under 1 minute'],
            ['skill_id' => 25, 'skill_name' => 'Box jumps over', 'stage' => 15, 'stage_label' => '38 reps under 1 minute'],
            ['skill_id' => 25, 'skill_name' => 'Box jumps over', 'stage' => 16, 'stage_label' => '41 reps under 1 minute'],
            ['skill_id' => 25, 'skill_name' => 'Box jumps over', 'stage' => 17, 'stage_label' => '43 reps under 1 minute'],
            ['skill_id' => 25, 'skill_name' => 'Box jumps over', 'stage' => 18, 'stage_label' => '45 reps under 1 minute'],
            ['skill_id' => 25, 'skill_name' => 'Box jumps over', 'stage' => 19, 'stage_label' => '48 reps under 1 minute'],
            ['skill_id' => 25, 'skill_name' => 'Box jumps over', 'stage' => 20, 'stage_label' => '50 reps under 1 minute'],
        ];

        DB::table('skills_stages')->insert($skillsStages);
    }
}
